package org.apache.commons.httpclient;

public class Header extends NameValuePair
{
  private boolean isAutogenerated = false;

  public Header()
  {
    this(null, null);
  }

  public Header(String paramString1, String paramString2)
  {
    super(paramString1, paramString2);
  }

  public Header(String paramString1, String paramString2, boolean paramBoolean)
  {
    super(paramString1, paramString2);
    this.isAutogenerated = paramBoolean;
  }

  public HeaderElement[] getElements()
  {
    return HeaderElement.parseElements(getValue());
  }

  public HeaderElement[] getValues()
    throws HttpException
  {
    return HeaderElement.parse(getValue());
  }

  public boolean isAutogenerated()
  {
    return this.isAutogenerated;
  }

  public String toExternalForm()
  {
    StringBuffer localStringBuffer = new StringBuffer();
    if (getName() == null)
    {
      str = "";
      localStringBuffer = localStringBuffer.append(str).append(": ");
      if (getValue() != null)
        break label61;
    }
    label61: for (String str = ""; ; str = getValue())
    {
      return str + "\r\n";
      str = getName();
      break;
    }
  }

  public String toString()
  {
    return toExternalForm();
  }
}

/* Location:           C:\Users\User\dex2jar-2.0\dex\qting\classes-dex2jar.jar
 * Qualified Name:     org.apache.commons.httpclient.Header
 * JD-Core Version:    0.6.2
 */